### ISSUE TITLE
output error on command line

### ISSUE THREAD

**Issue by xaryow** [IndonesianDev/whatsapp-bot#15]
(node:4980) UnhandledPromiseRejectionWarning: ReferenceError: updateJson is not defined
    at messageLog (C:\Users\admin\Desktop\BOT-WASAP\utils\index.js:17:38)
    at C:\Users\admin\Desktop\BOT-WASAP\index.js:129:9
    at Client.<anonymous> (C:\Users\admin\Desktop\BOT-WASAP\node_modules\@open-wa\wa-automate\dist\api\Client.js:630:92)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\admin\Desktop\BOT-WASAP\node_modules\@open-wa\wa-automate\dist\api\Client.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlvioAdjiJanuar** [comment]
updateJson ?

**Comment by xaryow** [comment]
> updateJson ?

nah ga ngerti saya juga, soalnya saya ngikutin semua cara install yg ada di readme

**Comment by AlvioAdjiJanuar** [comment]
Udah ane apus tuh

**Comment by AlvioAdjiJanuar** [comment]
y
